# Generated by Django 2.1.3 on 2018-12-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(choices=[('TE', 'Technology'), ('ED', 'Education'), ('EN', 'Entertainment'), ('DB', 'DjangoBlog')], default='blog', max_length=2),
        ),
    ]
