# Generated by Django 2.1.3 on 2018-12-01 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tags',
            new_name='tags_content',
        ),
    ]
