# Generated by Django 2.1.3 on 2018-12-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181201_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags_content',
            field=models.CharField(choices=[('TE', 'Technology'), ('ED', 'Education'), ('EN', 'Entertainment'), ('DB', 'DjangoBlog')], default='django-blog', max_length=2),
        ),
    ]
