# Generated by Django 2.1.3 on 2018-12-01 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181201_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags_content',
        ),
        migrations.AddField(
            model_name='tags',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='blog.Post'),
        ),
    ]
