# Generated by Django 2.1.3 on 2018-12-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20181201_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='tags',
            field=models.TextField(default='django-blog'),
        ),
    ]
