# Generated by Django 2.1.3 on 2018-12-01 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20181201_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='blog.Post'),
        ),
    ]
