# Generated by Django 2.1.3 on 2018-12-02 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20181201_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='post',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
