# Generated by Django 2.1.3 on 2018-12-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20181202_0627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagging',
            name='post',
        ),
        migrations.RemoveField(
            model_name='tagging',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tagged_blog',
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(to='blog.Tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Tagging',
        ),
    ]
