# Generated by Django 2.1.3 on 2018-12-02 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20181202_0637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='blog_tag',
        ),
    ]
