# Generated by Django 2.1.3 on 2018-12-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20181202_0644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='blog_tag',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(default='django-blog', max_length=50),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
